// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// VehiclePlatformSalesAdapter is an autogenerated mock type for the VehiclePlatformSalesAdapter type
type VehiclePlatformSalesAdapter struct {
	mock.Mock
}

// CreateVehicle provides a mock function with given fields: ctx, vehicleID, brand, model, color, year, price
func (_m *VehiclePlatformSalesAdapter) CreateVehicle(ctx context.Context, vehicleID string, brand string, model string, color string, year int, price float64) error {
	ret := _m.Called(ctx, vehicleID, brand, model, color, year, price)

	if len(ret) == 0 {
		panic("no return value specified for CreateVehicle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, float64) error); ok {
		r0 = rf(ctx, vehicleID, brand, model, color, year, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVehiclePlatformSalesAdapter creates a new instance of VehiclePlatformSalesAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVehiclePlatformSalesAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *VehiclePlatformSalesAdapter {
	mock := &VehiclePlatformSalesAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
